// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55-aRMSHDIIVtT4X_pHPc1L84uakz84g',
    appId: '1:921017024158:web:e123c27d7e480a479dc58f',
    messagingSenderId: '921017024158',
    projectId: 'fir-flutter-2e0da',
    authDomain: 'fir-flutter-2e0da.firebaseapp.com',
    storageBucket: 'fir-flutter-2e0da.firebasestorage.app',
    measurementId: 'G-WXB6XFHH4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7H30Iek5H5qkflGhhjSdmU7iWGO8tTI',
    appId: '1:921017024158:android:a89e2ae6f2287b679dc58f',
    messagingSenderId: '921017024158',
    projectId: 'fir-flutter-2e0da',
    storageBucket: 'fir-flutter-2e0da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjlERDx49M-4qKckXfHOeSupUdXst3q8',
    appId: '1:921017024158:ios:65e42d02ee696c499dc58f',
    messagingSenderId: '921017024158',
    projectId: 'fir-flutter-2e0da',
    storageBucket: 'fir-flutter-2e0da.firebasestorage.app',
    iosBundleId: 'com.example.myDaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjlERDx49M-4qKckXfHOeSupUdXst3q8',
    appId: '1:921017024158:ios:65e42d02ee696c499dc58f',
    messagingSenderId: '921017024158',
    projectId: 'fir-flutter-2e0da',
    storageBucket: 'fir-flutter-2e0da.firebasestorage.app',
    iosBundleId: 'com.example.myDaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA55-aRMSHDIIVtT4X_pHPc1L84uakz84g',
    appId: '1:921017024158:web:bd2d90ddd84083929dc58f',
    messagingSenderId: '921017024158',
    projectId: 'fir-flutter-2e0da',
    authDomain: 'fir-flutter-2e0da.firebaseapp.com',
    storageBucket: 'fir-flutter-2e0da.firebasestorage.app',
    measurementId: 'G-0KXDDDH32N',
  );
}
